[2024-11-03T01:28:25.358+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-03T01:28:25.486+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: songs_preprocessing.load_data_task manual__2024-11-03T01:28:22.262941+00:00 [queued]>
[2024-11-03T01:28:25.493+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: songs_preprocessing.load_data_task manual__2024-11-03T01:28:22.262941+00:00 [queued]>
[2024-11-03T01:28:25.493+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-03T01:28:25.512+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_task> on 2024-11-03 01:28:22.262941+00:00
[2024-11-03T01:28:25.518+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=526) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-03T01:28:25.520+0000] {standard_task_runner.py:63} INFO - Started process 543 to run task
[2024-11-03T01:28:25.519+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'songs_preprocessing', 'load_data_task', 'manual__2024-11-03T01:28:22.262941+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpv6co7g31']
[2024-11-03T01:28:25.521+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask load_data_task
[2024-11-03T01:28:25.557+0000] {task_command.py:426} INFO - Running <TaskInstance: songs_preprocessing.load_data_task manual__2024-11-03T01:28:22.262941+00:00 [running]> on host 4a174f3124db
[2024-11-03T01:28:25.630+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='songs_preprocessing' AIRFLOW_CTX_TASK_ID='load_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T01:28:22.262941+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-03T01:28:22.262941+00:00'
[2024-11-03T01:28:25.631+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-03T01:28:28.448+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-03T01:28:28.449+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/src/song_recommendation.py", line 16, in load_data
    subprocess.run(command, shell=True, check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'curl -L -o ../../data/dataset.csv 'https://docs.google.com/uc?export=download&id=1zckGHmd_tJfyMqePfol0L-lIScstOCh9'' returned non-zero exit status 23.
[2024-11-03T01:28:28.471+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=songs_preprocessing, task_id=load_data_task, run_id=manual__2024-11-03T01:28:22.262941+00:00, execution_date=20241103T012822, start_date=20241103T012825, end_date=20241103T012828
[2024-11-03T01:28:28.493+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task load_data_task (Command 'curl -L -o ../../data/dataset.csv 'https://docs.google.com/uc?export=download&id=1zckGHmd_tJfyMqePfol0L-lIScstOCh9'' returned non-zero exit status 23.; 543)
[2024-11-03T01:28:28.531+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-03T01:28:28.564+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-03T01:28:28.569+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
