[2024-11-02T20:11:39.493+0000] {processor.py:157} INFO - Started process (PID=50) to work on /opt/airflow/dags/airflow.py
[2024-11-02T20:11:39.494+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T20:11:39.584+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:11:39.583+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T20:11:39.776+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:11:39.751+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-11-02T20:11:39.791+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T20:11:40.178+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow.py took 0.829 seconds
[2024-11-02T20:14:05.432+0000] {processor.py:157} INFO - Started process (PID=45) to work on /opt/airflow/dags/airflow.py
[2024-11-02T20:14:05.459+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T20:14:05.545+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:14:05.529+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T20:14:05.638+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:14:05.597+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-11-02T20:14:05.652+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T20:14:06.180+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow.py took 0.803 seconds
[2024-11-02T20:14:58.436+0000] {processor.py:157} INFO - Started process (PID=106) to work on /opt/airflow/dags/airflow.py
[2024-11-02T20:14:58.483+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T20:14:58.508+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:14:58.507+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T20:14:58.567+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:14:58.557+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-11-02T20:14:58.582+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T20:14:58.779+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow.py took 0.350 seconds
[2024-11-02T20:15:38.539+0000] {processor.py:157} INFO - Started process (PID=144) to work on /opt/airflow/dags/airflow.py
[2024-11-02T20:15:38.569+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T20:15:38.668+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:15:38.608+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T20:15:38.770+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:15:38.743+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-11-02T20:15:38.792+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T20:15:39.568+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow.py took 1.156 seconds
[2024-11-02T20:16:19.414+0000] {processor.py:157} INFO - Started process (PID=191) to work on /opt/airflow/dags/airflow.py
[2024-11-02T20:16:19.437+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T20:16:19.478+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:16:19.458+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T20:16:19.654+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:16:19.567+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-11-02T20:16:19.676+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T20:16:20.117+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow.py took 0.828 seconds
[2024-11-02T20:16:59.549+0000] {processor.py:157} INFO - Started process (PID=240) to work on /opt/airflow/dags/airflow.py
[2024-11-02T20:16:59.588+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T20:16:59.640+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:16:59.639+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T20:16:59.806+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:16:59.786+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-11-02T20:16:59.842+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T20:17:00.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow.py took 0.762 seconds
[2024-11-02T20:17:41.524+0000] {processor.py:157} INFO - Started process (PID=280) to work on /opt/airflow/dags/airflow.py
[2024-11-02T20:17:41.532+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T20:17:41.560+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:17:41.555+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T20:17:41.585+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:17:41.579+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-11-02T20:17:41.586+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T20:17:41.703+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow.py took 0.273 seconds
[2024-11-02T20:18:29.470+0000] {processor.py:157} INFO - Started process (PID=335) to work on /opt/airflow/dags/airflow.py
[2024-11-02T20:18:29.482+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T20:18:29.516+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:18:29.497+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T20:18:29.586+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:18:29.548+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-11-02T20:18:29.612+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T20:18:30.038+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow.py took 0.663 seconds
[2024-11-02T20:19:12.431+0000] {processor.py:157} INFO - Started process (PID=385) to work on /opt/airflow/dags/airflow.py
[2024-11-02T20:19:12.436+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T20:19:12.447+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:19:12.445+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T20:19:12.455+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:19:12.452+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-11-02T20:19:12.455+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T20:19:12.507+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow.py took 0.091 seconds
[2024-11-02T20:19:57.188+0000] {processor.py:157} INFO - Started process (PID=437) to work on /opt/airflow/dags/airflow.py
[2024-11-02T20:19:57.227+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T20:19:57.278+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:19:57.270+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T20:19:57.330+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:19:57.329+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-11-02T20:19:57.331+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T20:19:57.654+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow.py took 0.556 seconds
[2024-11-02T20:20:42.666+0000] {processor.py:157} INFO - Started process (PID=483) to work on /opt/airflow/dags/airflow.py
[2024-11-02T20:20:42.693+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T20:20:42.732+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:20:42.732+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T20:20:42.893+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:20:42.851+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-11-02T20:20:42.907+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T20:20:43.355+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow.py took 0.812 seconds
[2024-11-02T20:21:32.999+0000] {processor.py:157} INFO - Started process (PID=535) to work on /opt/airflow/dags/airflow.py
[2024-11-02T20:21:33.010+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T20:21:33.096+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:21:33.068+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T20:21:33.186+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:21:33.149+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-11-02T20:21:33.187+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T20:21:33.533+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow.py took 0.572 seconds
[2024-11-02T20:22:19.086+0000] {processor.py:157} INFO - Started process (PID=585) to work on /opt/airflow/dags/airflow.py
[2024-11-02T20:22:19.102+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T20:22:19.107+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:22:19.106+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T20:22:19.122+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:22:19.112+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-11-02T20:22:19.123+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T20:22:19.302+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow.py took 0.260 seconds
[2024-11-02T20:23:00.950+0000] {processor.py:157} INFO - Started process (PID=629) to work on /opt/airflow/dags/airflow.py
[2024-11-02T20:23:00.986+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T20:23:01.055+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:23:01.052+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T20:23:01.109+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:23:01.085+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-11-02T20:23:01.123+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T20:23:01.748+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow.py took 0.890 seconds
[2024-11-02T20:23:53.872+0000] {processor.py:157} INFO - Started process (PID=685) to work on /opt/airflow/dags/airflow.py
[2024-11-02T20:23:53.893+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T20:23:53.911+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:23:53.908+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T20:23:53.935+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:23:53.927+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-11-02T20:23:53.936+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T20:23:54.156+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow.py took 0.291 seconds
[2024-11-02T20:24:46.695+0000] {processor.py:157} INFO - Started process (PID=741) to work on /opt/airflow/dags/airflow.py
[2024-11-02T20:24:46.707+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T20:24:46.768+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:24:46.752+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T20:24:46.865+0000] {logging_mixin.py:151} INFO - [2024-11-02T20:24:46.830+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py)
[2024-11-02T20:24:46.912+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T20:24:47.510+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow.py took 0.925 seconds
